### PR TITLE
added country support to genderize 

### PR DESCRIPTION
**Pull request by MarHai**
following https://genderize.io/#localization

### CODE REVIEW

**Comment by MarHai** [comment]
Hi @lmullen, not sure whether I did this the right way but here's my contribution in order to use genderize more sophistically (i.e., making use of its country support as well as being able to provide an API key). The Travis CI currently fails but it does so also on your last commit (i.e., it should not be related to my pull request).

**Comment by lmullen** [comment]
Thanks for the PR, @MarHai. The Travis CI problems were minor and are fixed on master. Could you please pull in the changes from master to this PR?

**Comment by MarHai** [comment]
Might be a stupid question but ... how?

**Comment by lmullen** [comment]
Something like this might be helpful: https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request

**Comment by MarHai** [comment]
Although it should now be rebased (thanks!), there is still a travis error ...

**Pull request closed without merging**
